# accelerometer pipeline configuration

import os
from pathlib import Path

DATA_DIR = Path("data/accelerometer/raw")
ACCELEROMTER_FILE_FORMAT = "*.pkl"  


EXAMPLE_DATA_FILE = "801_1_accelerometer.pkl"
EXAMPLE_DATA_PATH = DATA_DIR / EXAMPLE_DATA_FILE

SAMPLING_FREQ = 100

DRIFT_WINDOW_SIZE = 50

BANDPASS_LOWCUT = 1.0
BANDPASS_HIGHCUT = 30.0
BANDPASS_FREQ_RESOLUTION = 1.0

SEGMENT_WINDOW_SIZE = 100
SEGMENT_PERCENT_OVERLAP = 1.0

PEAK_LOW_FREQ = 3.0
PEAK_HIGH_FREQ = 8.0
AR_ORDER = 6
PROMINENCE_PERCENT = 10.0
ABS_POWER_THRESHOLD = 0.0
RELATIVE_POWER_THRESHOLD_PERCENT = 0.0

SMOOTHING_WINDOW = 51

FEATURE_THRESHOLD = 3.5

FEATURE_EXTRACTION_DURATION_THRESHOLD = 3.0
