name: pd_tremor_modern
channels:
  - conda-forge
  - defaults
dependencies:
  # Python Core
  - python=3.10
  - pip

  # Scientific Computing Stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - spectrum

  # Deep Learning Core
  - tensorflow
  - keras

  # Additional Packages
  - jupyter
  - ipykernel
  - mne
  - h5py
  - seaborn
  - openpyxl
  - xlrd
  - pillow
  - imageio
  - scikit-image

  - pip:
    - mne_icalabel
    - autoreject